nome = input('Escreva seu nome: ')
idade = input('Escreva sua idade: ')
print('Olá pequeno gafanhoto, é um prazer te conhecer!')
print('Então {}, Você vem sempre aqui?'.format(nome), 'Tem {} anos certo?'.format(idade))
resp1 = input()